### ISSUE TITLE
Global epg

### ISSUE THREAD

**Issue by irihox** [iptv-org/epg#1174] opened 2022-10-09 20:46 UTC
### Description

- Not every playlist has links that are from a single country/source.
- Some apps do not accept more than 1 xmltv source.

Due to the reasons above, having a "merged" global xml file would be great. File size may be large, but it is a downside some are willing to take.

**Comment by freearhey** [comment] 2022-10-10 11:08
Duplicate of #708

**Closed by freearhey** 2022-10-10 11:08 UTC
Labels: 💡 feature request
