### ISSUE TITLE
MoreMax East

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/epg#1797] opened 2023-01-23 23:13 UTC
### Source

https://www.tvpassport.com/tv-listings/stations/moremax-eastern-hd/7097

### Channels

MoreMaxEast.us

### Notes

Adding to TVPassport please ? It was added to another links already

**Comment by ajanes3** [comment] 2023-01-24 19:55
This already exists in tvpassport.

**Comment by spotanjo3** [comment] 2023-01-24 20:05
> This already exists in tvpassport.

Sorry. I edited it. Its East now. You can update it now. Sorry about that.

**Comment by ajanes3** [comment] 2023-01-24 20:47
Duplicate of #1796

**Closed** 2023-01-24 21:08 UTC
Labels: 🗓 epg request

**Comment by spotanjo3** [comment] 2023-01-24 23:23
What about other epg lists that I posted and requested ? Just wonder. I will wait, of course. ^_^

**Comment by ajanes3** [comment] 2023-01-24 23:32
@spotanjo3 please see #1819
