### ISSUE TITLE
tvarenasport.com

### ISSUE THREAD

**Issue by uploadkom** [iptv-org/epg#2465] opened 2024-11-18 18:29 UTC
### Site

https://www.tvarenasport.com/

### Description

starting...
loading channels...
(node:2337755) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
  found 12 channel(s)
run #1:
  [1/24] tvarenasport.com (sr) - ArenaSport1Premium.rs - Nov 18, 2024 (0 programs)
    ERR: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
  [2/24] tvarenasport.com (sr) - ArenaSport1Premium.rs - Nov 19, 2024 (0 programs)
    ERR: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
  [3/24] tvarenasport.com (sr) - ArenaSport8.rs - Nov 19, 2024 (0 programs)
    ERR: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
  [4/24] tvarenasport.com (sr) - ArenaSport8.rs - Nov 18, 2024 (0 programs)
    ERR: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
  [5/24] tvarenasport.com (sr) - ArenaSport7.rs - Nov 19, 2024 (0 programs)
    ERR: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
  [6/24] tvarenasport.com (sr) - ArenaSport7.rs - Nov 18, 2024 (0 programs)
    ERR: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
  [7/24] tvarenasport.com (sr) - ArenaSport6.rs - Nov 19, 2024 (0 programs)
    ERR: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
  [8/24] tvarenasport.com (sr) - ArenaSport6.rs - Nov 18, 2024 (0 programs)
    ERR: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
  [9/24] tvarenasport.com (sr) - ArenaSport5.rs - Nov 19, 2024 (0 programs)
    ERR: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
  [10/24] tvarenasport.com (sr) - ArenaSport5.rs - Nov 18, 2024 (0 programs)
    ERR: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
  [11/24] tvarenasport.com (sr) - ArenaSport4.rs - Nov 19, 2024 (0 programs)
    ERR: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
  [12/24] tvarenasport.com (sr) - ArenaSport4.rs - Nov 18, 2024 (0 programs)
    ERR: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
  [13/24] tvarenasport.com (sr) - ArenaSport3.rs - Nov 19, 2024 (0 programs)
    ERR: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
  [14/24] tvarenasport.com (sr) - ArenaSport3.rs - Nov 18, 2024 (0 programs)
    ERR: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
  [15/24] tvarenasport.com (sr) - ArenaSport3Premium.rs - Nov 19, 2024 (0 programs)
    ERR: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
  [16/24] tvarenasport.com (sr) - ArenaSport3Premium.rs - Nov 18, 2024 (0 programs)
    ERR: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
  [17/24] tvarenasport.com (sr) - ArenaSport2.rs - Nov 19, 2024 (0 programs)
    ERR: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
  [18/24] tvarenasport.com (sr) - ArenaSport2.rs - Nov 18, 2024 (0 programs)
    ERR: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
  [19/24] tvarenasport.com (sr) - ArenaSport2Premium.rs - Nov 19, 2024 (0 programs)
    ERR: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
  [20/24] tvarenasport.com (sr) - ArenaSport2Premium.rs - Nov 18, 2024 (0 programs)
    ERR: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
  [21/24] tvarenasport.com (sr) - ArenaSport1x2.rs - Nov 19, 2024 (0 programs)
    ERR: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
  [22/24] tvarenasport.com (sr) - ArenaSport1x2.rs - Nov 18, 2024 (0 programs)
    ERR: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
  [23/24] tvarenasport.com (sr) - ArenaSport1.rs - Nov 19, 2024 (0 programs)
    ERR: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
  [24/24] tvarenasport.com (sr) - ArenaSport1.rs - Nov 18, 2024 (0 programs)
    ERR: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
  done in 00h 00m 05s

**Comment by freearhey** [comment] 2024-11-25 16:12
Duplicate of https://github.com/iptv-org/epg/issues/2266

**Closed by freearhey** 2024-11-25 16:12 UTC
Labels: broken guide
