### ISSUE TITLE
Us-local/tvtv.us  Broken

### ISSUE THREAD

**Issue by WaNgEr00** [iptv-org/epg#1120] opened 2022-09-19 23:00 UTC
### Guide

https://iptv-org.github.io/epg/guides/us-local/tvtv.us.epg.xml.gz

### Description

Ive not been getting any updates from any of the tvtv sources for 3 days.

**Comment by RevGear** [comment] 2022-09-20 08:39
Duplicate of #1106

**Closed by RevGear** 2022-09-20 08:39 UTC
Labels: ⚠️ broken guide
