### ISSUE TITLE
gh-pages (shallow update not allowed) deploy error

### ISSUE THREAD

**Issue by mcastellaneta** [iptv-org/epg#773] opened 2022-05-04 09:45 UTC
I have noticed that many times the creation of guides fails due to this error. In particular, I am referring to the error in the GitHub action guidatv.sky.it #95.

` ! [remote rejected] github-pages-deploy-action/6pc8m68jz -> gh-pages (shallow update not allowed)`
`error: failed to push some refs to 'https://github.com/iptv-org/epg.git'`

Could we do something to prevent or mitigate this ?

**Comment by freearhey** [comment] 2022-05-04 11:58
Well, I'll try to update [JamesIves/github-pages-deploy-action](https://github.com/JamesIves/github-pages-deploy-action) to the latest version today. It seems to have recently added an [option](https://github.com/JamesIves/github-pages-deploy-action/releases/tag/v4.3.0) to allow automatic redeployment in case of errors. Let's hope this will be enough.

**Comment by freearhey** [comment] 2022-05-05 11:02
Unfortunately the update didn't help.

The error itself occurs at this stage:

https://github.com/iptv-org/epg/blob/a2e140358ba002ddcaf3225bb5b8e4fe2b08f672/.github/workflows/_load.yml#L44-L53

And I believe the cause of this error is the same as described here: https://github.com/JamesIves/github-pages-deploy-action/issues/1000. But unfortunately the proposed solution to use concurrency field is not suitable for us as it will just stop all other workflow in a queue when a conflict occurs.

**Comment by mcastellaneta** [comment] 2022-05-05 13:31
The documentation of [JamesIves/github-pages-deploy-action](https://github.com/JamesIves/github-pages-deploy-action/blame/dev/README.md#L165) states that the `force` key should be turned on by default. Have you already tried disabling it by setting `force:false` in the file?

**Comment by freearhey** [comment] 2022-05-09 10:33
The error seems to have disappeared after the update. 
So I'm closing this for now, but if the problem occurs again I'll reopen issue.

**Closed by freearhey** 2022-05-09 10:33 UTC
