### ISSUE TITLE
Why was the by country EPG removed?

### ISSUE THREAD

**Issue by ExperiencersInternational** [iptv-org/epg#1685] opened 2023-01-14 00:26 UTC
### Description

I'm working on my own TV guide and it has some channels not covered by your service, but it's targeted specifically for the UK: https://experiencersinternational.github.io/tvsetup. Since you've changed how the EPG works, less channels now show programming guide information.

Is there any chance that you might go back on this change?

**Comment by freearhey** [comment] 2023-01-14 09:46
Duplicate of #1655

**Closed by freearhey** 2023-01-14 09:46 UTC
Labels: ❓ question

**Comment by ExperiencersInternational** [comment] 2023-01-14 14:55
@freearhey, it's all good but a lot of the IPTV services I've used doesn't have the best EPG support.

For TVirl, it works great, but Live Channels keeps being a f***ing pain by only showing OTA stuff.

For Cosmi TV, which seems to be the next best thing for me atm, despite me inputting two different guides (since some of my channels are radio ones that you don't support, so I have to make my own guides for those), it only shows the first one.
