### ISSUE TITLE
Why the big change?

### ISSUE THREAD

**Issue by s-digweed** [iptv-org/epg#1658] opened 2023-01-11 19:16 UTC
### Description

Hi 

Obviously we all appreciate the hardwork that goes into the guides on a daily basis.

But why were the Jan 3rd changes made?

The country guides were working fine and the legacy source guides were also working fine on the forked F640 page.

Now I get it that the combined country guides+sources didn't work because of the language region issues. But if a change had to happen, why not keep both as were and give the users the choice to mix-and-match?

Thanks!

**Comment by jovanemarques** [comment] 2023-01-12 04:34
True.. I have no ideia how to find my Canadian channels between all those English epg now

**Comment by freearhey** [comment] 2023-01-12 07:22
@jovanemarques A complete list of Canadian channels with links to available EPGs can be found via iptv-org.github.io: https://iptv-org.github.io/?q=country:CA%20guides:%3E0

**Comment by jovanemarques** [comment] 2023-01-12 22:30
> 

Hey. That was really helpful. Thank you.

**Comment by freearhey** [comment] 2023-01-13 08:50
Duplicate of #1655

**Closed by freearhey** 2023-01-13 08:50 UTC
Labels: ❓ question

**Comment by Penguy-droid** [comment] 2023-01-16 06:30
Is there a master epg url with all the countries in it if it's no longer done individually by country ?
