### ISSUE TITLE
ITV1

### ISSUE THREAD

**Issue by Smark223** [iptv-org/epg#1425] opened 2022-11-28 10:59 UTC
### Channel ID

ITV1.uk

### Source

https://virgintvgo.virginmedia.com/en/tv/tv-guide.html

### Notes

ITV2, 3, 4 and Be EPGs are in the guide but ITV1 is missing

**Comment by freearhey** [comment] 2022-11-28 11:55
Duplicate of #1424

**Closed by freearhey** 2022-11-28 11:55 UTC
Labels: 🗓 epg request
